### ISSUE TITLE
[Check Request] CtsProcessorAffinityPercentage

### ISSUE THREAD

**Issue by lbec34** [dpaulson45/HealthChecker#574] opened 2021-03-29 09:53 UTC
**Is your request related to a problem? Please describe.**
We have the following on the HTML report 

CtsProcessorAffinityPercentage | 15 Error: This can cause an impact to the server's search performance. This should only be used a temporary fix if no other options are available vs a long term solution.

**Describe Check Request**
This setting has been modified related to the following technote 
https://www.admin-enclave.com/en/articles/exchange/308-configure-finetune-the-microsoft-exchange-search-indexing-feature.html
https://social.technet.microsoft.com/Forums/systemcenter/en-US/61e67bd4-5868-4b94-9be5-8a2b602a2fa7/high-cpu-parserserverexe?forum=exchangesvradmin
1-Launch registry editor
2-Go to path HKLM\SOFTWARE\Microsoft\ExchangeServer\V15\Search\SystemParameters
3-Create a DWORD by name CtsProcessorAffinityPercentage
4-Configure the value to 15 (decimal)
5-Restart Exchange Search Host Controller service and Microsoft Exchange Search service on the server.

My question is : is it relevant to remove this setting or can we leave it ? The change was made to improve users search performance

Thank you

Kind regards

**Comment by dpaulson45** [comment] 2021-03-29 15:47
@lbec34 that setting is **not** meant to improve your search performance. In fact it ends up slowing down your performance of search by limiting it. 

If you are seeing high CPU occur on your server caused by search, you have an underlying issue. That might be you are over subscribed to other possible issues. This key is only intended to help you get past a pain point while you address the root of your issue.

**Comment by dpaulson45** [comment] 2021-04-13 14:52
closing issue as answer is provided.

**Closed by dpaulson45** 2021-04-13 14:52 UTC
Labels: question
