### ISSUE TITLE
Script never fully executes and stuck on Invoke-WebRequest

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#228] opened 2019-09-19 17:00 UTC
Customer reported that the script was running for about 10 minutes and wasn't moving forward. Since they didn't display the Script version right away, we were likely stuck within the Test-ScriptVersion function. Looked up Invoke-WebRequest, and determined that we should timeout after 15 second to get the DNS query, but if the value is greater than 0 but less that 15 seconds, it can take 15 seconds or more before a WebException is thrown, and your request times out. 

Need to determine if we can reproduce this issue by setting a host file to the actual public IP address. If we are able to reproduce that issue, then we need to address this within the script. 

If we aren't able to reproduce this issue, then we can likely close out this issue. However, keep note of it for future possible issues. 

@lusassl-msft  could you investigate this?

**Comment by lusassl-msft** [comment] 2019-09-20 11:09
Tried to reproduce this issue with no success. I've tried several ways to break the function and the longest timeout I've seen during my testings was for about 60 seconds when pointing my servers DNS to a non-existing system within the network. The timeout was caused by some other functions which were not able resolve internal addresses for AD etc. . When the run called the Test-ScriptVersion function it works as designed and within a short time frame. So I don't think we have an issue here. It could also be possible that the Test-Connection cmdlet takes a little bit longer. We do ICMP here and go through a maximum of 128 hops (by default). ICMP may sometimes a little bit difficult depending on how companies route the packets or so. 
It would be helpful to get the verbose output to better understand what's going wrong. 
Results for testings with Invoke-WebRequest -TimeoutSec 15 are looking good. So we should implement this to make sure that we fail after a maximum of 15 seconds. I'll create a pull request to add this parameter. Starting next week I'll be on vacation. Can keep on working on this issue after my return in about 3 weeks.

**Comment by dpaulson45** [comment] 2019-09-20 14:10
Yeah, the one customer that was running into this issue, i just had someone comment out the line that called Test-ScriptVersion and then the script worked just fine. So maybe getting some additional debug/verbose information in that function would be helpful for the next time this occurs.

**Comment by lusassl-msft** [comment] 2019-09-20 14:21
We can implement a switch to run the script without version check? This makes it easier to handle cases in which the script run not properly because of network restrictions, because there is no need to modify the code and comment the function out? HealthChecker.ps1 -SkipVersionCheck or so. What do you think?

**Comment by dpaulson45** [comment] 2019-09-20 14:39
We could do that, or at least just bypass the network check and only do the local check against how old the file is. 

Could maybe make it more advanced and make the online check a background worker task and then after 30 seconds if we don't get results back cancel the request then move on.

**Comment by lusassl-msft** [comment] 2019-09-20 14:48
Sounds like a plan. If this once is not urgent, I can take care of this after my return.

**Comment by dpaulson45** [comment] 2019-09-20 14:59
Yeah, that is fine to do that after you get back.

**Comment by lusassl-msft** [comment] 2019-09-20 15:02
Okay. Please assign to me 😎

**Closed** 2019-12-17 21:38 UTC
Labels: Assigned To: lusassl-msft, Needs Investigation, Resolved
